name: "Dev env instructions"
on:
  pull_request:
  push:
    branches: [latest]
jobs:
  nix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v1

    - run: nix run .# -- --version

    - run: nix develop --command bash -c "tox -e py310"

  pixi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: set up pixi
      uses: prefix-dev/setup-pixi@v0.5.1
      with:
        pixi-version: v0.13.0
        cache: true

    - name: run tests for 3.10
      shell: pixi run bash {0}
      run: tox -e py310
