name: "Dev env instructions"
on:
  pull_request:
  push:
    branches: [latest]
jobs:
  nix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4
    - name: Run the Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@v1

    - run: nix run .# -- --version

    - run: nix develop --command bash -c "tox -e py310"

  mamba:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: cache conda
      uses: actions/cache@v4
      env:
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        python-version: "3.10"
        auto-update-conda: false
        auto-activate-base: false
        activate-environment: true

    - name: install dependencies
      shell: bash -l {0}
      run: |
        conda install conda-lock
        conda-lock --lockfile pixi.lock render -p linux-64
        conda create -n sourmash_dev --file conda-linux-64.lock

    - name: run tests for 3.10
      shell: bash -l {0}
      run: |
        conda activate sourmash_dev
        tox -e py310
